; Logger Configuration File
; Generated automatically by logger system

[logger]
; logger level: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = DEBUG

; output to console: true, false, yes, no, 1, 0
output_console = true

; output to file: true, false, yes, no, 1, 0
output_file = false

; logger file path(relative path)
log_file_path = ./log_output.txt

; [INFO]: modify the ini file and restart the program to work
